export default function Head() {
    return (
      <>
        <title>Tmdb-Movie</title>
        <meta content="width=device-width, initial-scale=1" name="viewport" />
        <meta
          name="description"
          content="Generated by create next app and Made with ❤️ by Ümit Uysal"
        />
        <link rel="icon" href="../favicon.ico" />
      </>
    );
  }